project:
  type: website

website:
  title: "Meucci Ilunga"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: analysis.qmd
        text: Sample Data Analysis

format:
  html:
    theme: morph
    css: styles.css
    toc: true
    link-decoration: underline